name: stock_tracker
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  data_table_2: ^2.5.15
  flutter:
    sdk: flutter
  intl: ^0.19.0
  open_file: ^3.3.2

  path_provider: ^2.1.3
  pdf: ^3.10.8
  sqflite: ^2.3.2
  sqflite_common: ^2.5.3
  sqflite_common_ffi: ^2.3.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
